version: '3'

services:
  catworks-router:
    image: nginx:latest
    container_name: catworks-router
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - catworks-routed
    environment:
      - NGINX_HOST=catworks.dev
      - NGINX_PORT=80

networks:
  catworks-routed:
    external: true
    driver: bridge
