version: '3'

services:
  catworks-router:
    image: nginx:latest
    container_name: catworks-router
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /usr/src/app:/usr/src/app:ro
      - ./site/src:/www:ro
    ports:
      - "443:443"
    networks:
      - catworks-routed
    environment:
      - NGINX_HOST=catworks.dev
      - NGINX_PORT=443

  catworks-mongo:
    image: mongo:latest
    container_name: catworks-mongo
    restart: on-failure
    entrypoint: ["/usr/bin/mongod", "--config", "/data/config/ssl.conf"]
    env_file:
      - ./mongo.env
    networks:
      - catworks-routed
    ports:
      - "27017:27017"
    volumes:
      - catworks-mongo-data:/data/db
      - catworks-mongo-log:/var/log/mongodb
      - /usr/src/app:/data/ssl
      - ./mongo/ssl.conf:/data/config/ssl.conf
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  catworks-mongo-data:
  catworks-mongo-log:

networks:
  catworks-routed:
    external: true
    driver: bridge
