name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: vm-1

    steps:
      - uses: actions/checkout@v3

      - name: Run via compose
        run: docker compose up -d --force-recreate --remove-orphans
