name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: vm-1
    environment: main

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run via compose
        env:
          MONGO_ROOT: ${{ secrets.MONGO_ROOT }}
          MONGO_ROOT_PWD: ${{ secrets.MONGO_ROOT_PWD }}
          MONGO_ADMIN: ${{ secrets.MONGO_ADMIN }}
          MONGO_ADMIN_PWD: ${{ secrets.MONGO_ADMIN_PWD }}
        run: docker compose up -d --force-recreate --remove-orphans

